Rename clang-format to dvlt-format
devialet/3rdparty_llvm pull request #1
Opened 2017-01-23 14:40 UTC by MatthieuCOLLETTE

As we plan to make some modifications on our side, we prefer renaming
clang-format to dvlt-format

2017-01-29 12:58 UTC, dguillois requested changes

2017-01-29 12:58 UTC, dguillois commented on CMakeLists.txt
> +
revert this modification

2017-01-29 12:58 UTC, dguillois commented on CMakeLists.txt
> +  "Semicolon-separated list of projects to build (${LLVM_ALL_PROJECTS}), or \"all\".")
and this one too

2017-01-30 13:12 UTC, MatthieuCOLLETTE commented on CMakeLists.txt
> +
My editor removes empty spaces ...

2017-01-30 13:14 UTC, MatthieuCOLLETTE commented on CMakeLists.txt
> +  "Semicolon-separated list of projects to build (${LLVM_ALL_PROJECTS}), or \"all\".")
My editor replaces tabs with spaces ...

2017-01-31 08:44 UTC, dguillois approved these changes

2017-02-01 14:54 UTC, merged